-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛 조회

SELECT FLAVOR
FROM(
SELECT J.FLAVOR AS FLAVOR, SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) AS TOTAL
FROM JULY AS J JOIN FIRST_HALF AS F USING(FLAVOR)
GROUP BY FLAVOR
ORDER BY TOTAL DESC
LIMIT 3
    ) AS NEW_TABLE