# 완료된 중고 거래의 총금액이 70만 원 이상인 사람
# 총 거래그램액을 기준으로 오름차순 정렬

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER AS UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS = "DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES